/**
 * MITRE ATT&CK technique definitions database.
 *
 * Each entry follows the ATT&CK framework structure:
 *   Tactic  ->  Technique  ->  Sub-technique (optional)
 */

export interface TechniqueDefinition {
  /** Full technique ID, e.g. "T1055" or "T1055.001". */
  id: string;
  /** Parent technique ID (same as id when there is no sub-technique). */
  techniqueId: string;
  /** Sub-technique ID fragment, e.g. "001", or null. */
  subTechniqueId: string | null;
  /** ATT&CK tactic (kill-chain phase). */
  tactic: string;
  /** Human-readable name. */
  name: string;
  /** Short description. */
  description: string;
  /** Relevant data sources. */
  dataSources: string[];
  /** Associated platforms. */
  platforms: string[];
}

/**
 * Comprehensive ATT&CK technique catalogue used by the mapper.
 */
export const TECHNIQUE_DATABASE: ReadonlyArray<TechniqueDefinition> = [
  // ── Execution ──────────────────────────────────────────────────────────
  {
    id: 'T1059',
    techniqueId: 'T1059',
    subTechniqueId: null,
    tactic: 'Execution',
    name: 'Command and Scripting Interpreter',
    description: 'Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries.',
    dataSources: ['Command', 'Process', 'Module'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1059.001',
    techniqueId: 'T1059',
    subTechniqueId: '001',
    tactic: 'Execution',
    name: 'PowerShell',
    description: 'Adversaries may abuse PowerShell commands and scripts for execution.',
    dataSources: ['Command', 'Process', 'Module', 'Script'],
    platforms: ['Windows'],
  },
  {
    id: 'T1059.003',
    techniqueId: 'T1059',
    subTechniqueId: '003',
    tactic: 'Execution',
    name: 'Windows Command Shell',
    description: 'Adversaries may abuse the Windows command shell (cmd.exe) for execution.',
    dataSources: ['Command', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1059.005',
    techniqueId: 'T1059',
    subTechniqueId: '005',
    tactic: 'Execution',
    name: 'Visual Basic',
    description: 'Adversaries may abuse Visual Basic (VB) for execution.',
    dataSources: ['Command', 'Process', 'Module', 'Script'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1059.006',
    techniqueId: 'T1059',
    subTechniqueId: '006',
    tactic: 'Execution',
    name: 'Python',
    description: 'Adversaries may abuse Python commands and scripts for execution.',
    dataSources: ['Command', 'Process'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1059.007',
    techniqueId: 'T1059',
    subTechniqueId: '007',
    tactic: 'Execution',
    name: 'JavaScript',
    description: 'Adversaries may abuse JavaScript for execution.',
    dataSources: ['Command', 'Process', 'Module', 'Script'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1204',
    techniqueId: 'T1204',
    subTechniqueId: null,
    tactic: 'Execution',
    name: 'User Execution',
    description: 'An adversary may rely upon specific actions by a user in order to gain execution.',
    dataSources: ['Process', 'File', 'Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1204.002',
    techniqueId: 'T1204',
    subTechniqueId: '002',
    tactic: 'Execution',
    name: 'Malicious File',
    description: 'An adversary may rely upon a user opening a malicious file in order to gain execution.',
    dataSources: ['Process', 'File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1047',
    techniqueId: 'T1047',
    subTechniqueId: null,
    tactic: 'Execution',
    name: 'Windows Management Instrumentation',
    description: 'Adversaries may abuse WMI to execute malicious commands and payloads.',
    dataSources: ['Command', 'Process', 'Network Traffic'],
    platforms: ['Windows'],
  },
  {
    id: 'T1053.005',
    techniqueId: 'T1053',
    subTechniqueId: '005',
    tactic: 'Execution',
    name: 'Scheduled Task',
    description: 'Adversaries may abuse the Windows Task Scheduler to perform task scheduling for initial or recurring execution.',
    dataSources: ['Command', 'Process', 'Scheduled Job'],
    platforms: ['Windows'],
  },
  // ── Persistence ────────────────────────────────────────────────────────
  {
    id: 'T1547.001',
    techniqueId: 'T1547',
    subTechniqueId: '001',
    tactic: 'Persistence',
    name: 'Registry Run Keys / Startup Folder',
    description: 'Adversaries may achieve persistence by adding a program to a startup folder or referencing it with a Registry run key.',
    dataSources: ['Windows Registry', 'File', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1547.004',
    techniqueId: 'T1547',
    subTechniqueId: '004',
    tactic: 'Persistence',
    name: 'Winlogon Helper DLL',
    description: 'Adversaries may abuse Winlogon helper DLLs for persistence.',
    dataSources: ['Windows Registry', 'Module', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1547.009',
    techniqueId: 'T1547',
    subTechniqueId: '009',
    tactic: 'Persistence',
    name: 'Shortcut Modification',
    description: 'Adversaries may create or modify shortcuts to run a program during system boot or user login.',
    dataSources: ['File', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1543.003',
    techniqueId: 'T1543',
    subTechniqueId: '003',
    tactic: 'Persistence',
    name: 'Windows Service',
    description: 'Adversaries may create or modify Windows services to repeatedly execute malicious payloads as part of persistence.',
    dataSources: ['Windows Registry', 'Process', 'Service'],
    platforms: ['Windows'],
  },
  {
    id: 'T1546.001',
    techniqueId: 'T1546',
    subTechniqueId: '001',
    tactic: 'Persistence',
    name: 'Change Default File Association',
    description: 'Adversaries may change file associations to execute arbitrary programs.',
    dataSources: ['Windows Registry', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1546.003',
    techniqueId: 'T1546',
    subTechniqueId: '003',
    tactic: 'Persistence',
    name: 'WMI Event Subscription',
    description: 'Adversaries may establish persistence via WMI event subscriptions.',
    dataSources: ['WMI', 'Process', 'Command'],
    platforms: ['Windows'],
  },
  {
    id: 'T1546.015',
    techniqueId: 'T1546',
    subTechniqueId: '015',
    tactic: 'Persistence',
    name: 'Component Object Model Hijacking',
    description: 'Adversaries may establish persistence by executing malicious content via hijacking COM object references.',
    dataSources: ['Windows Registry', 'Module', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1136',
    techniqueId: 'T1136',
    subTechniqueId: null,
    tactic: 'Persistence',
    name: 'Create Account',
    description: 'Adversaries may create an account to maintain access to victim systems.',
    dataSources: ['User Account', 'Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Privilege Escalation ───────────────────────────────────────────────
  {
    id: 'T1055',
    techniqueId: 'T1055',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Process Injection',
    description: 'Adversaries may inject code into processes in order to evade process-based defenses as well as possibly elevate privileges.',
    dataSources: ['Process', 'Module'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1055.001',
    techniqueId: 'T1055',
    subTechniqueId: '001',
    tactic: 'Defense Evasion',
    name: 'Dynamic-link Library Injection',
    description: 'Adversaries may inject DLLs into processes to evade defenses and elevate privileges.',
    dataSources: ['Process', 'Module'],
    platforms: ['Windows'],
  },
  {
    id: 'T1055.003',
    techniqueId: 'T1055',
    subTechniqueId: '003',
    tactic: 'Defense Evasion',
    name: 'Thread Execution Hijacking',
    description: 'Adversaries may inject malicious code into hijacked processes to evade detection.',
    dataSources: ['Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1055.012',
    techniqueId: 'T1055',
    subTechniqueId: '012',
    tactic: 'Defense Evasion',
    name: 'Process Hollowing',
    description: 'Adversaries may inject malicious code into suspended and hollowed processes to evade detection.',
    dataSources: ['Process'],
    platforms: ['Windows'],
  },
  // ── Defense Evasion ────────────────────────────────────────────────────
  {
    id: 'T1027',
    techniqueId: 'T1027',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Obfuscated Files or Information',
    description: 'Adversaries may attempt to make an executable or file difficult to discover or analyze by encrypting, encoding, or otherwise obfuscating its contents.',
    dataSources: ['File', 'Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1027.001',
    techniqueId: 'T1027',
    subTechniqueId: '001',
    tactic: 'Defense Evasion',
    name: 'Binary Padding',
    description: 'Adversaries may use binary padding to add junk data and change the on-disk representation of malware.',
    dataSources: ['File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1027.002',
    techniqueId: 'T1027',
    subTechniqueId: '002',
    tactic: 'Defense Evasion',
    name: 'Software Packing',
    description: 'Adversaries may perform software packing to conceal their code.',
    dataSources: ['File'],
    platforms: ['Windows', 'macOS'],
  },
  {
    id: 'T1070',
    techniqueId: 'T1070',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Indicator Removal',
    description: 'Adversaries may delete or modify artifacts to remove evidence of their presence.',
    dataSources: ['File', 'Process', 'Windows Registry', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1070.004',
    techniqueId: 'T1070',
    subTechniqueId: '004',
    tactic: 'Defense Evasion',
    name: 'File Deletion',
    description: 'Adversaries may delete files left behind by their actions.',
    dataSources: ['File', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1070.006',
    techniqueId: 'T1070',
    subTechniqueId: '006',
    tactic: 'Defense Evasion',
    name: 'Timestomp',
    description: 'Adversaries may modify file time attributes to hide malware or tools.',
    dataSources: ['File'],
    platforms: ['Windows', 'Linux'],
  },
  {
    id: 'T1574.002',
    techniqueId: 'T1574',
    subTechniqueId: '002',
    tactic: 'Defense Evasion',
    name: 'DLL Side-Loading',
    description: 'Adversaries may execute their own malicious payloads by side-loading DLLs.',
    dataSources: ['Module', 'Process', 'File'],
    platforms: ['Windows'],
  },
  {
    id: 'T1574.001',
    techniqueId: 'T1574',
    subTechniqueId: '001',
    tactic: 'Defense Evasion',
    name: 'DLL Search Order Hijacking',
    description: 'Adversaries may execute their own malicious payloads by hijacking the search order used to load DLLs.',
    dataSources: ['Module', 'Process', 'File'],
    platforms: ['Windows'],
  },
  {
    id: 'T1140',
    techniqueId: 'T1140',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Deobfuscate/Decode Files or Information',
    description: 'Adversaries may use obfuscated files or information to hide artifacts of an intrusion.',
    dataSources: ['File', 'Process', 'Script'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1562.001',
    techniqueId: 'T1562',
    subTechniqueId: '001',
    tactic: 'Defense Evasion',
    name: 'Disable or Modify Tools',
    description: 'Adversaries may disable security tools to avoid possible detection of their tools and activities.',
    dataSources: ['Process', 'Service', 'Windows Registry', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1562.004',
    techniqueId: 'T1562',
    subTechniqueId: '004',
    tactic: 'Defense Evasion',
    name: 'Disable or Modify System Firewall',
    description: 'Adversaries may disable or modify system firewalls to bypass network controls.',
    dataSources: ['Firewall', 'Command', 'Process'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1036',
    techniqueId: 'T1036',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Masquerading',
    description: 'Adversaries may attempt to manipulate features of their artifacts to make them appear legitimate or benign.',
    dataSources: ['File', 'Process', 'Service'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1036.005',
    techniqueId: 'T1036',
    subTechniqueId: '005',
    tactic: 'Defense Evasion',
    name: 'Match Legitimate Name or Location',
    description: 'Adversaries may match or approximate the name or location of legitimate files when naming malicious files.',
    dataSources: ['File', 'Process'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1112',
    techniqueId: 'T1112',
    subTechniqueId: null,
    tactic: 'Defense Evasion',
    name: 'Modify Registry',
    description: 'Adversaries may interact with the Windows Registry to hide configuration information or to remove information as part of cleanup.',
    dataSources: ['Windows Registry', 'Command', 'Process'],
    platforms: ['Windows'],
  },
  // ── Credential Access ──────────────────────────────────────────────────
  {
    id: 'T1003',
    techniqueId: 'T1003',
    subTechniqueId: null,
    tactic: 'Credential Access',
    name: 'OS Credential Dumping',
    description: 'Adversaries may attempt to dump credentials to obtain account login and credential material.',
    dataSources: ['Process', 'Command', 'File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1003.001',
    techniqueId: 'T1003',
    subTechniqueId: '001',
    tactic: 'Credential Access',
    name: 'LSASS Memory',
    description: 'Adversaries may attempt to access credential material stored in the process memory of LSASS.',
    dataSources: ['Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1003.002',
    techniqueId: 'T1003',
    subTechniqueId: '002',
    tactic: 'Credential Access',
    name: 'Security Account Manager',
    description: 'Adversaries may attempt to extract credential material from the SAM database.',
    dataSources: ['Command', 'Windows Registry', 'File'],
    platforms: ['Windows'],
  },
  {
    id: 'T1555',
    techniqueId: 'T1555',
    subTechniqueId: null,
    tactic: 'Credential Access',
    name: 'Credentials from Password Stores',
    description: 'Adversaries may search for common password storage locations to obtain user credentials.',
    dataSources: ['Process', 'Command', 'File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1555.003',
    techniqueId: 'T1555',
    subTechniqueId: '003',
    tactic: 'Credential Access',
    name: 'Credentials from Web Browsers',
    description: 'Adversaries may acquire credentials from web browsers by reading files specific to the target browser.',
    dataSources: ['Process', 'File', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1056.001',
    techniqueId: 'T1056',
    subTechniqueId: '001',
    tactic: 'Credential Access',
    name: 'Keylogging',
    description: 'Adversaries may log user keystrokes to intercept credentials.',
    dataSources: ['Process', 'Windows Registry'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Discovery ──────────────────────────────────────────────────────────
  {
    id: 'T1082',
    techniqueId: 'T1082',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'System Information Discovery',
    description: 'An adversary may attempt to get detailed information about the operating system and hardware.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1083',
    techniqueId: 'T1083',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'File and Directory Discovery',
    description: 'Adversaries may enumerate files and directories.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1057',
    techniqueId: 'T1057',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'Process Discovery',
    description: 'Adversaries may attempt to get information about running processes.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1012',
    techniqueId: 'T1012',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'Query Registry',
    description: 'Adversaries may interact with the Windows Registry to gather information about the system, configuration, and installed software.',
    dataSources: ['Windows Registry', 'Process', 'Command'],
    platforms: ['Windows'],
  },
  {
    id: 'T1016',
    techniqueId: 'T1016',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'System Network Configuration Discovery',
    description: 'Adversaries may look for details about the network configuration and settings.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1049',
    techniqueId: 'T1049',
    subTechniqueId: null,
    tactic: 'Discovery',
    name: 'System Network Connections Discovery',
    description: 'Adversaries may attempt to get a listing of network connections.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Lateral Movement ───────────────────────────────────────────────────
  {
    id: 'T1021.001',
    techniqueId: 'T1021',
    subTechniqueId: '001',
    tactic: 'Lateral Movement',
    name: 'Remote Desktop Protocol',
    description: 'Adversaries may use RDP to log into a computer using the Remote Desktop Protocol.',
    dataSources: ['Network Traffic', 'Logon Session', 'Process'],
    platforms: ['Windows'],
  },
  {
    id: 'T1021.002',
    techniqueId: 'T1021',
    subTechniqueId: '002',
    tactic: 'Lateral Movement',
    name: 'SMB/Windows Admin Shares',
    description: 'Adversaries may use SMB admin shares for lateral movement.',
    dataSources: ['Network Traffic', 'Logon Session'],
    platforms: ['Windows'],
  },
  // ── Collection ─────────────────────────────────────────────────────────
  {
    id: 'T1074.001',
    techniqueId: 'T1074',
    subTechniqueId: '001',
    tactic: 'Collection',
    name: 'Local Data Staging',
    description: 'Adversaries may stage collected data in a central location or directory on the local system prior to exfiltration.',
    dataSources: ['File', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1113',
    techniqueId: 'T1113',
    subTechniqueId: null,
    tactic: 'Collection',
    name: 'Screen Capture',
    description: 'Adversaries may attempt to take screen captures of the desktop.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1115',
    techniqueId: 'T1115',
    subTechniqueId: null,
    tactic: 'Collection',
    name: 'Clipboard Data',
    description: 'Adversaries may collect data stored in the clipboard.',
    dataSources: ['Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Command and Control ────────────────────────────────────────────────
  {
    id: 'T1071',
    techniqueId: 'T1071',
    subTechniqueId: null,
    tactic: 'Command and Control',
    name: 'Application Layer Protocol',
    description: 'Adversaries may communicate using application layer protocols to avoid detection.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1071.001',
    techniqueId: 'T1071',
    subTechniqueId: '001',
    tactic: 'Command and Control',
    name: 'Web Protocols',
    description: 'Adversaries may communicate using application layer protocols associated with web traffic.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1071.004',
    techniqueId: 'T1071',
    subTechniqueId: '004',
    tactic: 'Command and Control',
    name: 'DNS',
    description: 'Adversaries may communicate using the DNS application layer protocol.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1105',
    techniqueId: 'T1105',
    subTechniqueId: null,
    tactic: 'Command and Control',
    name: 'Ingress Tool Transfer',
    description: 'Adversaries may transfer tools or other files from an external system into a compromised environment.',
    dataSources: ['Network Traffic', 'File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1573',
    techniqueId: 'T1573',
    subTechniqueId: null,
    tactic: 'Command and Control',
    name: 'Encrypted Channel',
    description: 'Adversaries may employ an encryption algorithm to conceal command and control traffic.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1573.001',
    techniqueId: 'T1573',
    subTechniqueId: '001',
    tactic: 'Command and Control',
    name: 'Symmetric Cryptography',
    description: 'Adversaries may employ symmetric encryption to conceal C2 traffic.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1571',
    techniqueId: 'T1571',
    subTechniqueId: null,
    tactic: 'Command and Control',
    name: 'Non-Standard Port',
    description: 'Adversaries may communicate using a protocol and port pairing that are typically not associated.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1095',
    techniqueId: 'T1095',
    subTechniqueId: null,
    tactic: 'Command and Control',
    name: 'Non-Application Layer Protocol',
    description: 'Adversaries may use non-application layer protocols for communication between host and C2 server.',
    dataSources: ['Network Traffic'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Exfiltration ───────────────────────────────────────────────────────
  {
    id: 'T1041',
    techniqueId: 'T1041',
    subTechniqueId: null,
    tactic: 'Exfiltration',
    name: 'Exfiltration Over C2 Channel',
    description: 'Adversaries may steal data by exfiltrating it over an existing C2 channel.',
    dataSources: ['Network Traffic', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1048',
    techniqueId: 'T1048',
    subTechniqueId: null,
    tactic: 'Exfiltration',
    name: 'Exfiltration Over Alternative Protocol',
    description: 'Adversaries may steal data by exfiltrating it over a different protocol than the existing C2 channel.',
    dataSources: ['Network Traffic', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1567',
    techniqueId: 'T1567',
    subTechniqueId: null,
    tactic: 'Exfiltration',
    name: 'Exfiltration Over Web Service',
    description: 'Adversaries may use an existing, legitimate external Web service to exfiltrate data.',
    dataSources: ['Network Traffic', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  // ── Impact ─────────────────────────────────────────────────────────────
  {
    id: 'T1486',
    techniqueId: 'T1486',
    subTechniqueId: null,
    tactic: 'Impact',
    name: 'Data Encrypted for Impact',
    description: 'Adversaries may encrypt data on target systems or on large numbers of systems in a network to interrupt availability.',
    dataSources: ['File', 'Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1489',
    techniqueId: 'T1489',
    subTechniqueId: null,
    tactic: 'Impact',
    name: 'Service Stop',
    description: 'Adversaries may stop or disable services on a system.',
    dataSources: ['Service', 'Process', 'Command'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
  {
    id: 'T1490',
    techniqueId: 'T1490',
    subTechniqueId: null,
    tactic: 'Impact',
    name: 'Inhibit System Recovery',
    description: 'Adversaries may delete or remove built-in OS recovery data and features.',
    dataSources: ['Process', 'Command', 'File'],
    platforms: ['Windows', 'macOS', 'Linux'],
  },
];

/** Index techniques by ID for O(1) lookups. */
const techniqueIndex = new Map<string, TechniqueDefinition>();
for (const t of TECHNIQUE_DATABASE) {
  techniqueIndex.set(t.id, t);
}

/** Look up a technique by its ID. */
export function getTechniqueById(id: string): TechniqueDefinition | undefined {
  return techniqueIndex.get(id);
}

/** Find all techniques matching a tactic name. */
export function getTechniquesByTactic(tactic: string): TechniqueDefinition[] {
  const lowerTactic = tactic.toLowerCase();
  return TECHNIQUE_DATABASE.filter((t) => t.tactic.toLowerCase() === lowerTactic);
}
